# Generated by Django 5.2.1 on 2025-07-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title_color',
            field=models.CharField(max_length=7, null='true'),
            preserve_default='true',
        ),
    ]
